In [7]:
pip install numpy

Requirement already satisfied: numpy in c:\users\user\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import numpy as np
import pandas as pd

In [9]:
np.random.seed(101)
data_set = np.random.randint(0,101,(4,3))

In [10]:
data_set

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [11]:
index_set = ['Aba', 'Umuahia', 'Adamawa', 'Yola']
column_set =['Jan', 'Feb', 'March']

In [12]:
pd_series = pd.DataFrame(data=data_set,index= index_set, columns= column_set)

In [13]:
pd_series

         Jan  Feb  March
Aba       95   11     81
Umuahia   70   63     87
Adamawa   75    9     77
Yola      40    4     63

In [14]:
pd

In [15]:
pd_series.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Aba to Yola
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   March   4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [16]:
pwd

'C:\\Users\\User\\Downloads\\Python-Finance-QuantConnect\\03-Core-Pandas'

In [17]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8E0E-0AB3

 Directory of C:\Users\User\Downloads\Python-Finance-QuantConnect\03-Core-Pandas

26/03/2026  22:46    <DIR>          .
25/03/2026  08:24    <DIR>          ..
26/03/2026  22:44    <DIR>          .ipynb_checkpoints
25/03/2026  08:24    <DIR>          __pycache__
25/03/2026  16:35           565,986 00-Series.ipynb
25/03/2026  18:26           209,657 01-DataFrames.ipynb
26/03/2026  21:31           194,875 02-Conditional-Filtering.ipynb
26/03/2026  22:46           197,241 03-Useful-Methods.ipynb
25/03/2026  08:24            62,966 04-Combining-DataFrames.ipynb
25/03/2026  08:24            65,234 05-Inputs-and-Outputs.ipynb
25/03/2026  08:24             7,809 06-Core-Pandas-Finance-Exercise.ipynb
25/03/2026  08:24            66,826 07-Core-Pandas-Finance-Exercise-SOLUTIONS.ipynb
25/03/2026  08:24            18,676 constituents.csv
25/03/2026  08:24            73,270 constituents-financials.csv
25/03/2026  08:24                46 example.csv
25/03/2026  08:24             5,022 example.xlsx
25/03/2026  08:24        24,992,926 hotel_booking_data.csv
26/03/2026  21:52            72,721 Johnbosco.ipynb
25/03/2026  08:24               171 movie_scores.csv
25/03/2026  08:24            17,727 mpg.csv
25/03/2026  08:24             5,022 my_excel_file.xlsx
25/03/2026  08:24                46 new_file.csv
25/03/2026  08:24             5,021 new_workbook.xlsx
25/03/2026  08:24                46 newfile.csv
25/03/2026  08:24            52,132 reshaping_pivot.png
25/03/2026  08:24             5,459 RetailSales_BeerWineLiquor.csv
25/03/2026  08:24             1,302 Sales_Funnel_CRM.csv
25/03/2026  08:24             1,330 sample_table.html
25/03/2026  08:24               555 simple.html
25/03/2026  08:24            18,507 tips.csv
25/03/2026  18:21             5,413 Untitled.ipynb
              27 File(s)     26,645,986 bytes
               4 Dir(s)  139,008,086,016 bytes free

In [18]:
file_read =pd.read_csv("tips.csv")

In [19]:
file_read

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [20]:
file_read.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [21]:
file_read.index

RangeIndex(start=0, stop=244, step=1)

In [22]:
file_read.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [23]:
file_read.head(2)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608

In [24]:
file_read.tail(1).transpose()

                               243
total_bill                   18.78
tip                            3.0
sex                         Female
smoker                          No
day                           Thur
time                        Dinner
size                             2
price_per_person              9.39
Payer Name         Michelle Hardin
CC Number         3511451626698139
Payment ID                 Thur672

In [25]:
file_read[['total_bill']]

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [26]:
file_read

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [27]:
file_read= file_read.set_index('Payment ID')

In [28]:
file_read

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [29]:
file_read.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [30]:
file_read.loc['Sun2959']

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [31]:
# to pick collumns

In [32]:
file_read [['total_bill']]

            total_bill
Payment ID
Sun2959          16.99
Sun4608          10.34
Sun4458          21.01
Sun5260          23.68
Sun2251          24.59
...                ...
Sat2657          29.03
Sat1766          27.18
Sat3880          22.67
Sat17            17.82
Thur672          18.78

[244 rows x 1 columns]

In [33]:
file_read.head(0)

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size, price_per_person, Payer Name, CC Number]
Index: []

In [34]:
file_read['total price']= file_read['size']*file_read['price_per_person']

In [35]:
file_read.head(0)

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size, price_per_person, Payer Name, CC Number, total price]
Index: []

In [36]:
file_read.head(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,total price
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,16.98
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,10.35
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,21.00
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,23.68
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,24.60

In [37]:
file_read['total_bill'] > 30

Payment ID
Sun2959    False
Sun4608    False
Sun4458    False
Sun5260    False
Sun2251    False
           ...
Sat2657    False
Sat1766    False
Sat3880    False
Sat17      False
Thur672    False
Name: total_bill, Length: 244, dtype: bool

In [38]:
file_read[(file_read['total_bill'] > 45) | (file_read['smoker']== 'No')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,total price
Payment ID,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,16.98
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,10.35
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,21.00
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,23.68
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,24.60
...,...,...,...,...,...,...,...,...,...,...,...
Sat4615,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3534021246117605,10.08
Sat9777,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,35.82
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,29.04
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,17.82
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,18.78

In [42]:
str(123456789) [-10:]

'123456789'

In [64]:
def tip_good(tip):
    if tip > 1.5:
        return "good tip"
    else:
      return "bad tip"

In [65]:
import numpy as np
file_read['Tip_ Comment'] = np.vectorize(tip_good)(file_read['tip'])
file_read.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,total price,Tip_ Comment
Payment ID,,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,16.98,bad tip
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,10.35,good tip
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,21.00,good tip
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,23.68,good tip
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,24.60,good tip