In [284]:
# import the necessary library
import numpy as np

In [285]:
import pandas as pd

In [286]:
pwd

'C:\\Users\\User\\Downloads\\Python-Finance-QuantConnect\\03-Core-Pandas'

In [287]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8E0E-0AB3

 Directory of C:\Users\User\Downloads\Python-Finance-QuantConnect\03-Core-Pandas

02/04/2026  23:52    <DIR>          .
25/03/2026  08:24    <DIR>          ..
02/04/2026  23:13    <DIR>          .ipynb_checkpoints
25/03/2026  08:24    <DIR>          __pycache__
01/04/2026  12:27           565,986 00-Series.ipynb
25/03/2026  18:26           209,657 01-DataFrames.ipynb
26/03/2026  21:31           194,875 02-Conditional-Filtering.ipynb
01/04/2026  15:03           197,241 03-Useful-Methods.ipynb
01/04/2026  11:49            63,042 04-Combining-DataFrames.ipynb
01/04/2026  11:49            65,310 05-Inputs-and-Outputs.ipynb
27/03/2026  10:06             8,778 06-Core-Pandas-Finance-Exercise.ipynb
02/04/2026  20:36             8,365 06-Core-Pandas-Finance-Exercise-Copy1.ipynb
02/04/2026  23:51            72,359 07-Core-Pandas-Finance-Exercise-SOLUTIONS.ipynb
25/03/2026  08:24            18,676 constituents.csv
25/03/2026  08:24            73,270 constituents-financials.csv
02/04/2026  18:03            79,366 Data Frames with Pandas.ipynb
25/03/2026  08:24                46 example.csv
25/03/2026  08:24             5,022 example.xlsx
25/03/2026  08:24        24,992,926 hotel_booking_data.csv
25/03/2026  08:24               171 movie_scores.csv
25/03/2026  08:24            17,727 mpg.csv
25/03/2026  08:24             5,022 my_excel_file.xlsx
25/03/2026  08:24                46 new_file.csv
25/03/2026  08:24             5,021 new_workbook.xlsx
25/03/2026  08:24                46 newfile.csv
02/04/2026  23:52           163,295 Pandas first project in working with Data Frames.ipynb
25/03/2026  08:24            52,132 reshaping_pivot.png
25/03/2026  08:24             5,459 RetailSales_BeerWineLiquor.csv
25/03/2026  08:24             1,302 Sales_Funnel_CRM.csv
25/03/2026  08:24             1,330 sample_table.html
25/03/2026  08:24               555 simple.html
25/03/2026  08:24            18,507 tips.csv
25/03/2026  18:21             5,413 Untitled.ipynb
01/04/2026  14:34            27,629 Untitled1.ipynb
              30 File(s)     26,858,574 bytes
               4 Dir(s)  138,694,545,408 bytes free

In [288]:
df=pd.read_csv('constituents.csv')

In [289]:
df

    Symbol                    Name                  Sector
0      MMM              3M Company             Industrials
1      AOS         A.O. Smith Corp             Industrials
2      ABT     Abbott Laboratories             Health Care
3     ABBV             AbbVie Inc.             Health Care
4      ACN           Accenture plc  Information Technology
..     ...                     ...                     ...
500    XYL              Xylem Inc.             Industrials
501    YUM         Yum! Brands Inc  Consumer Discretionary
502    ZBH  Zimmer Biomet Holdings             Health Care
503   ZION           Zions Bancorp              Financials
504    ZTS                  Zoetis             Health Care

[505 rows x 3 columns]

In [290]:
df1= pd.read_csv('constituents-financials.csv')

In [291]:
df1

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...
...,...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,http://www.sec.gov/cgi-bin/browse-edgar?action...
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,http://www.sec.gov/cgi-bin/browse-edgar?action...
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,http://www.sec.gov/cgi-bin/browse-edgar?action...
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,http://www.sec.gov/cgi-bin/browse-edgar?action...
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [292]:
df.columns

Index(['Symbol', 'Name', 'Sector'], dtype='object')

In [293]:
df1.columns

Index(['Symbol', 'Price', 'Price/Earnings', 'Dividend Yield', 'Earnings/Share',
       '52 Week Low', '52 Week High', 'Market Cap', 'EBITDA', 'Price/Sales',
       'Price/Book', 'SEC Filings'],
      dtype='object')

In [294]:
df.info

<bound method DataFrame.info of     Symbol                    Name                  Sector
0      MMM              3M Company             Industrials
1      AOS         A.O. Smith Corp             Industrials
2      ABT     Abbott Laboratories             Health Care
3     ABBV             AbbVie Inc.             Health Care
4      ACN           Accenture plc  Information Technology
..     ...                     ...                     ...
500    XYL              Xylem Inc.             Industrials
501    YUM         Yum! Brands Inc  Consumer Discretionary
502    ZBH  Zimmer Biomet Holdings             Health Care
503   ZION           Zions Bancorp              Financials
504    ZTS                  Zoetis             Health Care

[505 rows x 3 columns]>

In [295]:
df1.info

<bound method DataFrame.info of     Symbol   Price  Price/Earnings  Dividend Yield  Earnings/Share  \
0      MMM  222.89           24.31        2.332862            7.92
1      AOS   60.24           27.76        1.147959            1.70
2      ABT   56.27           22.51        1.908982            0.26
3     ABBV  108.48           19.41        2.499560            3.29
4      ACN  150.51           25.47        1.714470            5.44
..     ...     ...             ...             ...             ...
500    XYL   70.24           30.94        1.170079            1.83
501    YUM   76.30           27.25        1.797080            4.07
502    ZBH  115.53           14.32        0.794834            9.01
503   ZION   50.71           17.73        1.480933            2.60
504    ZTS   71.51           32.80        0.682372            1.65

     52 Week Low  52 Week High    Market Cap        EBITDA  Price/Sales  \
0         259.77       175.490  138721055226  9.048000e+09     4.390271
1          68.39        48.925   10783419933  6.010000e+08     3.575483
2          64.60        42.280  102121042306  5.744000e+09     3.740480
3         125.86        60.050  181386347059  1.031000e+10     6.291571
4         162.60       114.820   98765855553  5.643228e+09     2.604117
..           ...           ...           ...           ...          ...
500        76.81        46.860   12915021000  7.220000e+08     2.726209
501        86.93        62.850   27003303098  2.289000e+09     6.313636
502       133.49       108.170   24454698119  2.007400e+09     3.164895
503        55.61        38.430   10670678640  0.000000e+00     3.794579
504        80.13        52.000   35991109776  1.734000e+09     9.280896

     Price/Book                                        SEC Filings
0         11.34  http://www.sec.gov/cgi-bin/browse-edgar?action...
1          6.35  http://www.sec.gov/cgi-bin/browse-edgar?action...
2          3.19  http://www.sec.gov/cgi-bin/browse-edgar?action...
3         26.14  http://www.sec.gov/cgi-bin/browse-edgar?action...
4         10.62  http://www.sec.gov/cgi-bin/browse-edgar?action...
..          ...                                                ...
500        5.31  http://www.sec.gov/cgi-bin/browse-edgar?action...
501      212.08  http://www.sec.gov/cgi-bin/browse-edgar?action...
502        2.39  http://www.sec.gov/cgi-bin/browse-edgar?action...
503        1.42  http://www.sec.gov/cgi-bin/browse-edgar?action...
504       18.09  http://www.sec.gov/cgi-bin/browse-edgar?action...

[505 rows x 12 columns]>

In [296]:
#get the first five info of the first and second data
df.head()

  Symbol                 Name                  Sector
0    MMM           3M Company             Industrials
1    AOS      A.O. Smith Corp             Industrials
2    ABT  Abbott Laboratories             Health Care
3   ABBV          AbbVie Inc.             Health Care
4    ACN        Accenture plc  Information Technology

In [297]:
df1.head()

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,SEC Filings
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,http://www.sec.gov/cgi-bin/browse-edgar?action...
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,http://www.sec.gov/cgi-bin/browse-edgar?action...
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,http://www.sec.gov/cgi-bin/browse-edgar?action...
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,http://www.sec.gov/cgi-bin/browse-edgar?action...
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,http://www.sec.gov/cgi-bin/browse-edgar?action...

In [298]:
df1= df1.drop( 'SEC Filings',axis=1)

In [299]:
df1

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62
...,...,...,...,...,...,...,...,...,...,...,...
500,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31
501,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08
502,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39
503,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42
504,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09

In [300]:
df1=df1.set_index('Symbol')

In [301]:
df1

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
Symbol,,,,,,,,,,
MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34
AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35
ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19
ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14
ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62
...,...,...,...,...,...,...,...,...,...,...
XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31
YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08
ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39
ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42
ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09

In [302]:
df1.nlargest(10,'Market Cap')
# this returns the information about the 10 companies with the largest market cap

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
Symbol,,,,,,,,,,
AAPL,155.15,16.86,1.579541,9.20,180.1000,131.1200,809508034020,7.938600e+10,3.458609,5.66
GOOGL,1007.71,31.48,0.000000,22.27,1198.0000,824.3000,733823966137,3.421700e+10,6.801692,4.70
GOOG,1001.52,40.29,0.000000,22.27,1186.8900,803.1903,728535558140,3.271400e+10,6.772653,4.67
MSFT,85.01,25.76,1.874791,2.97,96.0700,63.2200,689978437468,4.107900e+10,7.113097,9.49
AMZN,1350.50,296.16,0.000000,6.16,1498.0000,812.5000,685873374731,1.613200e+10,3.927053,24.28
FB,171.58,27.90,0.000000,5.39,195.3200,132.4400,523423036576,2.362400e+10,13.241967,7.08
JPM,107.88,15.43,1.984584,6.30,117.3529,81.6350,386613611000,0.000000e+00,3.371499,1.60
JNJ,126.36,17.31,2.556688,0.39,148.3200,113.1500,353062464971,2.243000e+10,4.632622,4.74
XOM,76.07,21.37,4.003120,1.88,89.3000,76.0500,326148660000,3.905200e+10,1.770194,1.85
BAC,29.74,16.34,1.536000,1.55,32.6700,22.0700,321478200969,0.000000e+00,3.201187,1.24

In [303]:
df1=df1.drop('GOOG',axis=0)

In [304]:
df1

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
Symbol,,,,,,,,,,
MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34
AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35
ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19
ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14
ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62
...,...,...,...,...,...,...,...,...,...,...
XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31
YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08
ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39
ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42
ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09

In [305]:
len(df1[df1['Dividend Yield']>4])
#checks the number of companies that have dividend Yield greater than 4

37

In [306]:
df1[df1['Dividend Yield']>4]

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book
Symbol,,,,,,,,,,
AES,10.06,9.96,4.961832,-1.72,12.0500,10.0000,6920851212,3.001000e+09,0.659514,2.20
T,35.57,12.14,5.415651,4.76,42.7000,32.5500,226713270000,4.965300e+10,1.408315,1.80
CNP,25.85,19.73,4.210926,1.00,30.4500,25.5100,11362043297,2.337000e+09,1.626262,3.21
CTL,16.20,8.35,12.661196,1.16,27.6100,13.1610,18237196861,5.577000e+09,1.479598,1.39
D,73.31,20.42,4.528200,4.91,85.3000,71.5900,47543571860,6.428000e+09,3.795421,2.96
DUK,74.32,16.70,4.784946,3.12,91.8000,72.9300,52078185682,9.895000e+09,2.934886,1.27
EIX,58.07,13.23,4.054280,3.96,83.3800,58.7600,19447670886,4.284000e+09,2.161095,1.59
ETR,72.02,10.65,4.892126,-3.26,87.9500,69.6300,13116894887,8.807000e+08,1.554312,1.54
XOM,76.07,21.37,4.003120,1.88,89.3000,76.0500,326148660000,3.905200e+10,1.770194,1.85
FE,30.64,11.18,4.673807,-14.49,35.2200,27.9300,13706075072,-5.067000e+09,1.299448,2.19
F,10.43,5.89,6.784387,1.90,13.4800,10.1900,42414328338,9.281000e+09,0.270541,1.26
GGP,21.62,13.86,4.005462,1.34,25.7200,18.8300,21018887283,1.740540e+09,17.003777,2.57
HCP,22.64,10.99,6.330197,1.33,33.6700,22.8000,10967755538,1.412684e+09,8.127109,1.97
HP,64.87,-54.51,4.149992,-1.20,75.0200,42.1600,7345243806,4.836730e+08,3.738586,1.62
HST,18.75,11.23,4.113111,1.02,21.5300,17.2600,14394715334,1.547000e+09,3.554913,2.02
ICE,67.00,22.95,5.429864,2.37,76.1378,56.8000,41373051167,3.103000e+09,9.619987,2.62
IRM,32.07,15.42,7.082580,0.46,41.5300,32.0500,9410249279,1.116140e+09,3.289863,4.97
KIM,14.01,9.28,7.713499,0.80,25.1500,14.3300,6180487499,7.011900e+08,7.050894,1.20
LB,47.77,12.77,4.886988,3.98,63.1000,35.0000,13862042842,2.329000e+09,1.706098,1403.38
L,46.05,15.99,4.513164,1.93,53.5900,45.0100,16111166935,0.000000e+00,1.580976,0.85
MAC,58.36,14.81,4.917760,3.43,69.7300,52.1200,8473119166,5.031830e+08,11.394877,2.24
M,24.00,7.67,6.098546,1.98,33.7300,17.4050,7541063495,2.446000e+09,0.455032,1.69
MAA,85.39,14.38,4.196520,2.86,110.9500,86.9500,9992628990,8.714830e+08,6.629107,1.60
NAVI,13.38,7.56,4.558404,1.01,16.9700,11.4810,3692691330,0.000000e+00,0.698658,1.02
OXY,68.47,195.63,4.408186,-0.75,78.0900,57.2000,53467692395,5.205000e+09,6.044895,NaN
OKE,54.40,34.00,5.443620,1.66,61.3600,47.1400,21988472489,1.851783e+09,2.615956,4.03
PM,100.39,22.36,4.328479,4.48,123.5500,96.6600,153580671803,1.180200e+10,2.757468,1318.70
PPL,29.52,12.83,5.219689,2.79,40.2000,29.2050,20839814845,3.937000e+09,3.749705,1.95
PSA,180.49,18.21,4.316159,6.81,232.2100,180.9254,32258539942,1.924803e+09,16.164170,6.56
O,47.56,15.54,5.372036,1.12,63.6000,48.8900,13784942453,1.075568e+09,15.588069,1.92
SCG,35.60,8.75,6.683033,4.16,71.2800,35.3100,5229448882,1.459000e+09,1.651705,0.92
STX,47.44,11.51,5.085772,2.58,56.4500,30.6000,14113197720,1.811000e+09,1.304856,13.33
SPG,152.18,13.56,5.036808,6.25,187.3500,150.1500,48139839531,4.411515e+09,8.754495,13.24
SO,43.40,15.78,5.353023,2.53,53.5100,42.6300,43497224128,6.012000e+09,2.508060,1.82
VTR,50.92,12.21,5.965641,1.86,72.3600,51.8000,18865999082,1.935931e+09,7.074050,1.76
VZ,49.04,13.08,4.626544,7.36,54.7700,42.8000,208092277044,4.574500e+10,1.645254,7.96
HCN,54.67,12.74,6.153846,2.81,78.1700,55.2900,20943679019,1.908253e+09,6.725218,1.49

In [307]:
df1[df1["Market Cap"] > 1e+11]["Earnings/Share"].mean()
# mean of earning per share ratio of companies with EBITDA higher than 1e + 4

np.float64(4.746470588235294)

In [308]:
(df1['Earnings/Share']>=0).sum()
#number of companies with positive earnings per share ratio

np.int64(453)

In [309]:
df1.columns

Index(['Price', 'Price/Earnings', 'Dividend Yield', 'Earnings/Share',
       '52 Week Low', '52 Week High', 'Market Cap', 'EBITDA', 'Price/Sales',
       'Price/Book'],
      dtype='object')

In [310]:
df1['Dividend Yield'].max()

12.661196

In [311]:
df1.nlargest(1,'Dividend Yield').iloc[0]
# shows the company with the highest dividend yield and it's 52 week high

Price             1.620000e+01
Price/Earnings    8.350000e+00
Dividend Yield    1.266120e+01
Earnings/Share    1.160000e+00
52 Week Low       2.761000e+01
52 Week High      1.316100e+01
Market Cap        1.823720e+10
EBITDA            5.577000e+09
Price/Sales       1.479598e+00
Price/Book        1.390000e+00
Name: CTL, dtype: float64

In [312]:
index = abs(df1["52 Week High"] - df1["52 Week Low"]).idxmax()
df1.loc[index]

Price             1.350500e+03
Price/Earnings    2.961600e+02
Dividend Yield    0.000000e+00
Earnings/Share    6.160000e+00
52 Week Low       1.498000e+03
52 Week High      8.125000e+02
Market Cap        6.858734e+11
EBITDA            1.613200e+10
Price/Sales       3.927053e+00
Price/Book        2.428000e+01
Name: AMZN, dtype: float64

In [313]:
df1['Spread']= abs(df1['52 Week High']-df1['52 Week Low'])

In [314]:
df1

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread
Symbol,,,,,,,,,,,
MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,84.280
AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,19.465
ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,22.320
ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,65.810
ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,47.780
...,...,...,...,...,...,...,...,...,...,...,...
XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,29.950
YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,24.080
ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,25.320
ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,17.180
ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,28.130

In [315]:
df1['Spread'].max()

685.5

In [316]:
df1.nlargest(1,'Spread')

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread
Symbol,,,,,,,,,,,
AMZN,1350.5,296.16,0.0,6.16,1498.0,812.5,685873374731,1.613200e+10,3.927053,24.28,685.5

In [317]:
df1[(df1['Price']>=50) & (df1['Price']<=100)]
#or you can use this code df1[df1['Price].between(50,100)]
# this is used  to check the prices between two prices

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread
Symbol,,,,,,,,,,,
AOS,60.24,27.76,1.147959,1.70,68.390,48.925,10783419933,6.010000e+08,3.575483,6.35,19.465
ABT,56.27,22.51,1.908982,0.26,64.600,42.280,102121042306,5.744000e+09,3.740480,3.19,22.320
ATVI,65.83,31.80,0.431903,1.28,74.945,38.930,52518668144,2.704000e+09,10.595120,5.16,36.015
AFL,83.25,12.24,2.429907,11.01,91.730,68.800,33422948000,0.000000e+00,1.542934,1.53,22.930
A,65.05,27.45,0.875698,2.10,75.000,49.230,21984606918,1.094000e+09,6.493563,4.56,25.770
...,...,...,...,...,...,...,...,...,...,...,...
XLNX,62.82,27.19,2.090488,2.32,77.260,54.990,17064975551,8.454680e+08,7.101206,7.22,22.270
XYL,70.24,30.94,1.170079,1.83,76.810,46.860,12915021000,7.220000e+08,2.726209,5.31,29.950
YUM,76.30,27.25,1.797080,4.07,86.930,62.850,27003303098,2.289000e+09,6.313636,212.08,24.080
ZION,50.71,17.73,1.480933,2.60,55.610,38.430,10670678640,0.000000e+00,3.794579,1.42,17.180
ZTS,71.51,32.80,0.682372,1.65,80.130,52.000,35991109776,1.734000e+09,9.280896,18.09,28.130

In [318]:
df1['Market Cap in Billion']=df1['Market Cap']/1000000000

In [319]:
df1

,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread,Market Cap in Billion
Symbol,,,,,,,,,,,,
MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,84.280,138.721055
AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,19.465,10.783420
ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,22.320,102.121042
ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,65.810,181.386347
ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,47.780,98.765856
...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,29.950,12.915021
YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,24.080,27.003303
ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,25.320,24.454698
ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,17.180,10.670679
ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,28.130,35.991110

In [320]:
df1[['Market Cap','Dividend Yield']].corr()

                Market Cap  Dividend Yield
Market Cap        1.000000       -0.003506
Dividend Yield   -0.003506        1.000000

In [321]:
df1.columns

Index(['Price', 'Price/Earnings', 'Dividend Yield', 'Earnings/Share',
       '52 Week Low', '52 Week High', 'Market Cap', 'EBITDA', 'Price/Sales',
       'Price/Book', 'Spread', 'Market Cap in Billion'],
      dtype='object')

In [322]:
df.columns

Index(['Symbol', 'Name', 'Sector'], dtype='object')

In [323]:
df3=pd.merge(df1,df,on='Symbol')

In [324]:
df3

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread,Market Cap in Billion,Name,Sector
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,84.280,138.721055,3M Company,Industrials
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,19.465,10.783420,A.O. Smith Corp,Industrials
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,22.320,102.121042,Abbott Laboratories,Health Care
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,65.810,181.386347,AbbVie Inc.,Health Care
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,47.780,98.765856,Accenture plc,Information Technology
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,29.950,12.915021,Xylem Inc.,Industrials
500,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,24.080,27.003303,Yum! Brands Inc,Consumer Discretionary
501,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,25.320,24.454698,Zimmer Biomet Holdings,Health Care
502,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,17.180,10.670679,Zions Bancorp,Financials
503,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,28.130,35.991110,Zoetis,Health Care

In [325]:
df3.columns

Index(['Symbol', 'Price', 'Price/Earnings', 'Dividend Yield', 'Earnings/Share',
       '52 Week Low', '52 Week High', 'Market Cap', 'EBITDA', 'Price/Sales',
       'Price/Book', 'Spread', 'Market Cap in Billion', 'Name', 'Sector'],
      dtype='object')

In [326]:
df3['Sector']

0                 Industrials
1                 Industrials
2                 Health Care
3                 Health Care
4      Information Technology
                ...
499               Industrials
500    Consumer Discretionary
501               Health Care
502                Financials
503               Health Care
Name: Sector, Length: 504, dtype: object

In [328]:
df3['Sector'].replace(['Information Technology'],['IT'],inplace=True)

In [329]:
df3

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread,Market Cap in Billion,Name,Sector
0,MMM,222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,84.280,138.721055,3M Company,Industrials
1,AOS,60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,19.465,10.783420,A.O. Smith Corp,Industrials
2,ABT,56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,22.320,102.121042,Abbott Laboratories,Health Care
3,ABBV,108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,65.810,181.386347,AbbVie Inc.,Health Care
4,ACN,150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,47.780,98.765856,Accenture plc,IT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,XYL,70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,29.950,12.915021,Xylem Inc.,Industrials
500,YUM,76.30,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,24.080,27.003303,Yum! Brands Inc,Consumer Discretionary
501,ZBH,115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,25.320,24.454698,Zimmer Biomet Holdings,Health Care
502,ZION,50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,17.180,10.670679,Zions Bancorp,Financials
503,ZTS,71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,28.130,35.991110,Zoetis,Health Care

In [277]:
num=100
'$'+ str(num)

'$100'

In [278]:
def price(num):
    return '$'+str(num)

In [330]:
df3['Price']=np.vectorize(price)(df3['Price'])
#add $ to the numbers in the price

In [331]:
df3

,Symbol,Price,Price/Earnings,Dividend Yield,Earnings/Share,52 Week Low,52 Week High,Market Cap,EBITDA,Price/Sales,Price/Book,Spread,Market Cap in Billion,Name,Sector
0,MMM,$222.89,24.31,2.332862,7.92,259.77,175.490,138721055226,9.048000e+09,4.390271,11.34,84.280,138.721055,3M Company,Industrials
1,AOS,$60.24,27.76,1.147959,1.70,68.39,48.925,10783419933,6.010000e+08,3.575483,6.35,19.465,10.783420,A.O. Smith Corp,Industrials
2,ABT,$56.27,22.51,1.908982,0.26,64.60,42.280,102121042306,5.744000e+09,3.740480,3.19,22.320,102.121042,Abbott Laboratories,Health Care
3,ABBV,$108.48,19.41,2.499560,3.29,125.86,60.050,181386347059,1.031000e+10,6.291571,26.14,65.810,181.386347,AbbVie Inc.,Health Care
4,ACN,$150.51,25.47,1.714470,5.44,162.60,114.820,98765855553,5.643228e+09,2.604117,10.62,47.780,98.765856,Accenture plc,IT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,XYL,$70.24,30.94,1.170079,1.83,76.81,46.860,12915021000,7.220000e+08,2.726209,5.31,29.950,12.915021,Xylem Inc.,Industrials
500,YUM,$76.3,27.25,1.797080,4.07,86.93,62.850,27003303098,2.289000e+09,6.313636,212.08,24.080,27.003303,Yum! Brands Inc,Consumer Discretionary
501,ZBH,$115.53,14.32,0.794834,9.01,133.49,108.170,24454698119,2.007400e+09,3.164895,2.39,25.320,24.454698,Zimmer Biomet Holdings,Health Care
502,ZION,$50.71,17.73,1.480933,2.60,55.61,38.430,10670678640,0.000000e+00,3.794579,1.42,17.180,10.670679,Zions Bancorp,Financials
503,ZTS,$71.51,32.80,0.682372,1.65,80.13,52.000,35991109776,1.734000e+09,9.280896,18.09,28.130,35.991110,Zoetis,Health Care